name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: Swatinem/rust-cache@v1

      # https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807878478
      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clippy with annotations
        uses: actions-rs/clippy-check@v1
        if: steps.check_permissions.outputs.has-permission
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets

      - name: Clippy without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --all-features --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        run: cargo test -- --include-ignored

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nightly rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Rustfmt check
        run: cargo +nightly fmt --check
